if (OS_LINUX)
    ADD_LOGICAL_TARGET("libcef_lib" "${CEF_LIB_DEBUG}" "${CEF_LIB_RELEASE}")

    add_executable(${CMAKE_PROJECT_NAME} ${PROJECT_SOURCES})
    SET_EXECUTABLE_TARGET_PROPERTIES(${CMAKE_PROJECT_NAME})

    target_link_libraries(${CMAKE_PROJECT_NAME} ${LINKED_LIBS} ${CEF_STANDARD_LIBS})

    set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES INSTALL_RPATH "$ORIGIN")
    set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES BUILD_WITH_INSTALL_RPATH TRUE)
    set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CEF_TARGET_OUT_DIR})

    if (EXISTS "${CEF_BINARY_DIR}/libminigbm.so")
        COPY_FILES("${CMAKE_PROJECT_NAME}" "libminigbm.so" "${CEF_BINARY_DIR}" "${CEF_TARGET_OUT_DIR}")
    endif ()

    SET_LINUX_SUID_PERMISSIONS("${CMAKE_PROJECT_NAME}" "${CEF_TARGET_OUT_DIR}/chrome-sandbox")
endif ()
